name: Course Feedback
description: Provide feedback on Level Up experience
title: "[Course Feedback]: "
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        See a typo on a slide? Wish breaks were longer? Have an idea for something to add to Level Up? Give us feedback here!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Provide your name, if you're comfortable, so we can follow up if we need more details.
      placeholder: Firstname Lastname
    validations:
      required: false
  - type: dropdown
    id: contenttype
    attributes:
      label: scope
      description: What module is your feedback about?
      options:
        - Overall (Default)
        - Logistics
        - Case Study
        - Kickoff
        - Closings
        - Team Formation
        - Lean and Agile Modeling
        - Human Centered Design
        - Giving and Receiving Feedback
        - Stories
        - Story Mapping
        - Definition of Ready
        - Story Splitting
        - Domain Models
        - System Operations
        - Mockups
        - Specification by Example
        - Definition of Done
        - Information Radiators
        - Activity Diagrams
        - GRASP and SOLID
        - Communication Diagrams
        - Design Class Diagrams
        - CI/CD and GitOps
        - ATDD
        - Test Doubles
        - UTDD
        - Pairing and Mobbing
        - Code Reviews
        - Sprint Review
        - Retrospective
        - Leadership
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What's your feedback?
      description: Keep it constructive. How can we do what WE do, but better? (Not, "this is how I would've done it").
      validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to use this repository only for LevelUp classroom work and not for any confidential or private company information.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
