name: Participant Registration
description: Register as a current Level Up participant
title: "[Registration]: "
labels: ["register"]
assignees:
  - octocat
body:
  - type: input
    id: contact
    attributes:
      label: First and Last Name
      description: Give us your first and last name, if you're comfortable. Otherwise, let an instructor know you've registered and what your GitHub ID is.
      placeholder: Firstname Lastname
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to use this repository only for LevelUp classroom work and not for any confidential or private company information.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true