name: Makefile CI

on:
  push:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with: 
        distribution: 'oracle'
        java-version: '17'
      
    - name: Install dependencies
      run: make bootstrap
      
    - name: Run tests and CI build
      run: ./gradlew test
  
  acceptance-test:
    runs-on: self-hosted
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with: 
        distribution: 'oracle'
        java-version: '17'

    - name: Install dependencies
      run: make bootstrap
      
    - name: Run acceptance tests
      run: ./gradlew cucumberCli

    - name: Make output dir
      if: ${{ always() }}
      run: mkdir -p ./output

    - name: Copy images to output dir
      if: ${{ always() }}
      run: cp -R src/test/resources/images output

    - name: Setup Pages
      if: always()
      uses: actions/configure-pages@v3
    - name: Upload pages artifact
      if: always()
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./output
    - name: Deploy to GitHub Pages
      if: always()
      id: deployment
      uses: actions/deploy-pages@v2