name: Makefile CI

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: make bootstrap
      
    - name: Run tests and CI build
      run: make test
  
  acceptance-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make bootstrap
      
    - name: Run acceptance tests
      run: make acceptance-test

    - name: Cache test output
      uses: actions/cache@v3
      with:
        path: ./output
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-test-output-dir
  
  publish-tests:
    needs: acceptance-test
    runs-on: ubuntu-latest

    steps:
    - name: Fetch cache test output
      uses: actions/cache@v3
      with:
        path: ./output
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-test-output-dir

    - name: Publish Tests
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
